# Generated by Django 3.2.12 on 2022-06-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='reply_time',
            field=models.DateField(blank=True, default=None),
        ),
    ]
