# Generated by Django 3.2.12 on 2022-06-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_reportpost_reply_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='reply_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
