# Generated by Django 3.2.12 on 2022-04-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
                ('top', models.BooleanField()),
            ],
        ),
    ]
