# Generated by Django 3.2.12 on 2022-04-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('au', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('captcha', models.CharField(max_length=6)),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
